// Code generated by github.com/activatedio/gen. DO NOT EDIT.

package yb

import (
	gorm "github.com/activatedio/datainfra/pkg/data/gorm"
	fx "go.uber.org/fx"
)

// Index collects constructors for implementations in an fx module
func Index() fx.Option {
	return fx.Module("example.data.yb", fx.Provide(gorm.NewDB, gorm.NewContextBuilder, NewLocationRepository, NewCategoryRepository, NewProductRepository, NewThemeRepository))
}
